global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using SyncroBackend.Models.Enums;
global using Microsoft.EntityFrameworkCore;
global using System.Reflection;
global using SyncroBackend.Models;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;